"""What makes two requests the same request, and which requests may be cached at all.

Everything in this phase that can be wrong in a way nobody notices is in this file. A
cache that misses when it could have hit costs money. A cache that hits when it should
have missed returns one request's answer to a different question, which is a correctness
bug wearing a performance improvement's clothes. The whole module is written so that the
first kind of mistake is the one it makes.

**The key is a deny-list, not an allow-list.** The obvious design names the fields that
matter - model, messages, system prompt, tools, temperature - and hashes those. It is the
wrong way round. A provider that adds an output-affecting field tomorrow would be silently
ignored by an allow-list, and two requests differing only in that field would collide: a
wrong hit. Hashing the whole body except a named few inverts the failure: an unrecognised
field changes the key, the lookup misses, and the request goes upstream. Extra misses cost
money. Wrong hits cost trust.

**Normalisation is structural only.** Sorting object keys is safe, because JSON objects
are unordered by definition and {"a":1,"b":2} and {"b":2,"a":1} are the same request.
Almost nothing else is. Prompt text is never trimmed, cased or collapsed: "Hello" and
"hello " are different inputs to a model and may produce different outputs, and a cache
that treats them as one has made that decision on the model's behalf. Lists keep their
order for the same reason - the order tool declarations are given in is part of the
prompt, and sorting `tools` would let two genuinely different requests share an entry.

**The tenant is inside the hash, not only in the query.** Entries are scoped per tenant
(see docs/threat-model.md), which the `WHERE tenant_id = ?` on the lookup
already enforces. Putting the tenant id in the hashed material as well means a wrong
predicate, a mistyped join or a future query that forgets the scope still cannot produce
a cross-tenant hit: the keys simply do not collide. It costs nothing and removes a whole
class of leak.

**The key carries a version.** Any change to what is hashed, or to how it is
canonicalised, changes the meaning of every key already stored. Bumping
`CACHE_KEY_VERSION` makes old entries unreachable rather than reinterpreted, so a
normalisation fix retires the entries it invalidates instead of serving them under rules
they were never written under.
"""

import hashlib
import json
import uuid
from typing import Any

# Bump on any change to what is hashed, or to how it is canonicalised. Old entries then
# become unreachable and age out by their TTL, rather than being read under new rules.
CACHE_KEY_VERSION = 1

# One provider today. Named rather than derived from the base URL, which differs between
# the mock and the real API and would otherwise invalidate the cache per environment.
PROVIDER = "gemini"

# Where a request ended up. These are metric label values and a ledger column's values,
# so the set is small, closed, and named in one place.
EXACT_HIT = "exact"
SEMANTIC_HIT = "semantic"
MISS = "miss"
BYPASS = "bypass"
CACHE_STATUSES = frozenset({EXACT_HIT, SEMANTIC_HIT, MISS, BYPASS})
HIT_STATUSES = frozenset({EXACT_HIT, SEMANTIC_HIT})

# Query parameters that describe the transport rather than the request. `alt=sse` picks
# the framing of the response and `key` is the caller's own credential; neither changes a
# single token of what the model produces. Every other parameter is hashed, so one this
# gateway has never heard of makes the key miss rather than being quietly ignored.
TRANSPORT_QUERY_PARAMS = frozenset({"alt", "key"})

# The separator between hashed fields. A control character, so no model name, tenant id
# or JSON document can contain one and shift the boundary between two fields.
FIELD_SEPARATOR = "\x1f"

# The only finish reason that means "the model said what it had to say". MAX_TOKENS is
# arguably reproducible too, but SAFETY, RECITATION and their relatives are policy
# decisions a provider revisits - and freezing one into a cache is how a product acquires
# a refusal it can never explain and never clear.
CACHEABLE_FINISH_REASON = "STOP"

# Gemini samples at temperature 1.0 when a request names none. Assuming 0 instead would
# quietly cache responses the provider generated by sampling, which is the exact failure
# the temperature ceiling exists to prevent.
PROVIDER_DEFAULT_TEMPERATURE = 1.0

# The field holding the conversation. Named once, because the semantic tier turns on
# removing exactly this key from the body and embedding it separately.
CONTENTS = "contents"


def canonical(value: Any) -> Any:
    """Normalise the parts of a JSON document that carry no meaning.

    Only two things are touched, and both are provably inert:

      * Numbers whose value is a whole number are written as integers, so
        `"temperature": 0` and `"temperature": 0.0` - which an encoder chooses between
        on the client's behalf - do not become two entries for one request.
      * Dictionary key order, handled by `sort_keys` on the way out.

    Lists keep their order and strings are returned untouched. See the module docstring.
    """
    # Before the float check: bool is a subclass of int, and True must stay a boolean.
    if isinstance(value, bool):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, dict):
        return {key: canonical(item) for key, item in value.items()}
    if isinstance(value, list):
        return [canonical(item) for item in value]
    return value


def canonical_json(value: Any) -> str | None:
    """`value` as one stable string, or None if it cannot be written as valid JSON.

    `allow_nan=False` is the guard that matters: `json.loads` happily accepts the
    JavaScript-isms `NaN` and `Infinity`, which have no canonical form and no equality
    anyone would want a cache key built on. Such a request is simply not cacheable.
    """
    try:
        return json.dumps(
            canonical(value),
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            allow_nan=False,
        )
    except (TypeError, ValueError):
        return None


def request_payload(body: bytes) -> dict[str, Any] | None:
    """The request body as a JSON object, or None if it is not one."""
    try:
        payload: Any = json.loads(body)
    except ValueError:
        return None
    return payload if isinstance(payload, dict) else None


def generation_config(payload: dict[str, Any]) -> dict[str, Any]:
    config = payload.get("generationConfig")
    return config if isinstance(config, dict) else {}


def temperature_of(payload: dict[str, Any], default: float) -> float:
    """The temperature this request will actually be served at.

    An absent temperature is the provider's default and not zero, which is why `default`
    is a setting rather than a literal: it is a fact about the upstream, and a gateway in
    front of a provider that defaults to greedy decoding would set it to 0.
    """
    value = generation_config(payload).get("temperature")
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return default
    return float(value)


def request_block_reason(
    payload: dict[str, Any] | None, *, max_temperature: float, assumed_temperature: float
) -> str | None:
    """Why this request may not touch the cache, or None if it may.

    A blocked request is neither looked up nor stored. A reason is returned rather than a
    boolean because it goes onto a span, and "why did the cache do nothing for this
    request" is a question somebody eventually asks of one specific request.
    """
    if payload is None:
        return "unparseable_body"
    if canonical_json(payload) is None:
        return "uncanonicalisable_body"
    if temperature_of(payload, assumed_temperature) > max_temperature:
        # Sampled output. Caching it would hand every later caller one draw from a
        # distribution the tenant asked to sample from, which changes what the product
        # does without changing a line of the tenant's code.
        return "temperature_above_ceiling"
    candidates = generation_config(payload).get("candidateCount")
    if isinstance(candidates, int) and not isinstance(candidates, bool) and candidates > 1:
        return "multiple_candidates"  # a request for variety, by definition
    return None


def response_block_reason(payload: dict[str, Any] | None) -> str | None:
    """Why this response may not be stored, or None if it may.

    Only a complete, successful, countable answer is worth keeping. Everything refused
    here is refused because replaying it later would be worse than making the call again.
    """
    if payload is None:
        return "unparseable_response"
    if "error" in payload:
        return "error_in_body"  # a provider can fail inside a 200; see usage.py
    candidates = payload.get("candidates")
    if not isinstance(candidates, list) or not candidates:
        # No candidates means generation was blocked and promptFeedback explains why.
        # That verdict belongs to the provider, freshly, every time.
        return "no_candidates"
    first = candidates[0]
    if not isinstance(first, dict):
        return "malformed_candidate"
    finish = first.get("finishReason")
    if finish != CACHEABLE_FINISH_REASON:
        return f"finish_reason_{str(finish).lower()}"
    if not isinstance(payload.get("usageMetadata"), dict):
        # Without token counts there is nothing to say what a hit saved, which is the
        # number this whole phase exists to produce.
        return "no_usage_metadata"
    if canonical_json(payload) is None:
        return "uncanonicalisable_response"
    return None


def query_material(items: list[tuple[str, str]]) -> str | None:
    """The output-affecting part of the query string, canonically.

    Sorted, because query parameter order is not meaningful, and the transport-only
    parameters are dropped. A parameter this gateway does not recognise is kept, so it
    changes the key and the request misses rather than colliding with one without it.
    """
    kept = sorted((name, value) for name, value in items if name not in TRANSPORT_QUERY_PARAMS)
    return canonical_json([list(pair) for pair in kept])


def cache_key(
    *, tenant_id: uuid.UUID, model: str, payload: dict[str, Any], query: str
) -> str | None:
    """The identity of this request, as 64 hex characters.

    The method is deliberately absent. `generateContent` and `streamGenerateContent`
    differ in how the same answer is framed on the wire, not in what the model produces,
    so one entry serves both and a streaming caller can be answered from a unary caller's
    entry. replay.py is what makes that safe: a hit is re-emitted in whichever shape the
    caller asked for.
    """
    body = canonical_json(payload)
    return None if body is None else digest("exact", tenant_id, model, query, body)


def digest(kind: str, tenant_id: uuid.UUID, model: str, query: str, body: str) -> str:
    """One hash, over fields that cannot be confused for one another.

    `kind` discriminates the two hashes here, so a request carrying no `contents` at all
    - where the whole body and the body-without-the-prompt are the same document - still
    produces two different values.
    """
    material = FIELD_SEPARATOR.join(
        [str(CACHE_KEY_VERSION), kind, PROVIDER, str(tenant_id), model, query, body]
    )
    return hashlib.sha256(material.encode()).hexdigest()


def params_key(
    *, tenant_id: uuid.UUID, model: str, payload: dict[str, Any], query: str
) -> str | None:
    """Everything about the request except what was actually asked.

    This is what makes the semantic tier safe. Similarity is measured over the prompt and
    over nothing else, so every other thing that changes an answer - the system
    instruction, the tool declarations, the temperature, the response schema, the model,
    the tenant - has to match exactly before two requests are ever compared. Without it a
    question asked under "answer in one word" could be served the answer it got under
    "answer in three paragraphs", because the two prompts are identical.
    """
    body = canonical_json({key: value for key, value in payload.items() if key != CONTENTS})
    return None if body is None else digest("params", tenant_id, model, query, body)


def prompt_text(payload: dict[str, Any]) -> str:
    """The conversation as one string, for the embedding model.

    The whole conversation and not merely the last turn: two requests ending in "and
    why?" are not the same question, and a cache that embedded only the last message
    would treat them as one. Roles are written in, so a line the user said and the same
    line the model said do not render identically.
    """
    turns = payload.get(CONTENTS)
    if isinstance(turns, dict):  # the API accepts a single turn as well as a list
        turns = [turns]
    if not isinstance(turns, list):
        return ""

    lines = []
    for turn in turns:
        if not isinstance(turn, dict):
            continue
        parts = turn.get("parts")
        text = " ".join(
            part["text"]
            for part in (parts if isinstance(parts, list) else [])
            if isinstance(part, dict) and isinstance(part.get("text"), str)
        )
        # `text.strip()`, not `text`: a turn holding only whitespace has nothing in it to
        # embed, and writing the role prefix anyway would turn "   " into the perfectly
        # matchable string "user:". An empty request has no business being similar to
        # anything, which is what semantic_block_reason then relies on.
        if text.strip():
            lines.append(f"{turn.get('role', 'user')}: {text}")
    return "\n".join(lines)


def has_only_text_parts(payload: dict[str, Any]) -> bool:
    """Whether every part of the conversation is text the embedding will actually see."""
    turns = payload.get(CONTENTS)
    if isinstance(turns, dict):
        turns = [turns]
    if not isinstance(turns, list):
        return False
    for turn in turns:
        if not isinstance(turn, dict):
            return False
        parts = turn.get("parts")
        if not isinstance(parts, list) or not parts:
            return False
        if any(not isinstance(part, dict) or "text" not in part for part in parts):
            return False
    return True


def semantic_block_reason(payload: dict[str, Any]) -> str | None:
    """Why this request may not be answered from a *similar* one, or None if it may.

    Stricter than the exact tier, and it has to be. An exact hit is justified by the
    request being byte-for-byte the same once normalised; a semantic hit is justified
    only by a number, and everything that number does not cover has to be excluded here.

    The part that is easy to miss: `contents` is excluded from the parameters hash,
    because the prompt is what similarity is measured over. Anything else living inside
    `contents` - an image, a file reference, a function response - is therefore covered
    by neither the hash nor the embedding, and two requests with identical text and
    different images would look like one request. A conversation that is not entirely
    text is refused for that reason.
    """
    if not prompt_text(payload).strip():
        return "no_prompt_text"
    if not has_only_text_parts(payload):
        return "non_text_parts"
    return None
