"""usage: streaming columns

Revision ID: 09625236705e
Revises: 50ef8333996e
Create Date: 2026-09-15 20:30:09.031980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09625236705e"
down_revision: str | Sequence[str] | None = "50ef8333996e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_records", sa.Column("upstream_ttfb_ms", sa.Integer(), nullable=True))
    op.add_column(
        "usage_records", sa.Column("streamed", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "usage_records",
        sa.Column("client_disconnected", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "client_disconnected")
    op.drop_column("usage_records", "streamed")
    op.drop_column("usage_records", "upstream_ttfb_ms")
    # ### end Alembic commands ###
