"""response cache

`cache_entries` holds one answer per normalised request, scoped to one tenant. The table
is disposable: every row can be regenerated by making the call again, so it cascades on
tenant delete where `usage_records` refuses to, and it may be truncated at any time.

No prompt text is stored. The request survives only as `cache_key`, a SHA-256 over its
normalised form (src/tollgate/cache/keys.py), which cannot be read back. The response is
stored whole, because that is the thing being cached.

The unique constraint on (tenant_id, cache_key) is also the lookup index - the read is
"this tenant, this key, not yet expired" - so no second index is created. `expires_at` is
deliberately left unindexed: the only query leading with it is the prune sweep, a rare
maintenance pass that is content with a sequential scan, and an index on it would instead
be written on every insert, which is the hot path.

`usage_records` gains two columns. `cache_status` records what the cache did with the
request, including the requests it turned away, so a hit rate has an honest denominator.
`cost_avoided_microcents` holds what a hit would have cost at today's prices; it is kept
apart from `cost_microcents` because adding a notional saving into the ledger's money
column would inflate every bill and every budget check that reads it.

Revision ID: c47e1b2a9f04
Revises: 40654c1b992e
Create Date: 2026-09-21 09:30:12.884210

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c47e1b2a9f04"
down_revision: str | Sequence[str] | None = "40654c1b992e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("thoughts_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hits", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name="fk_cache_entries_tenant_id_tenants",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_cache_entries"),
        sa.UniqueConstraint("tenant_id", "cache_key", name="uq_cache_entries_tenant_id"),
    )
    op.add_column("usage_records", sa.Column("cache_status", sa.String(length=16), nullable=True))
    op.add_column(
        "usage_records", sa.Column("cost_avoided_microcents", sa.BigInteger(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("usage_records", "cost_avoided_microcents")
    op.drop_column("usage_records", "cache_status")
    op.drop_table("cache_entries")
